# Numpy学习

## Array：

In [2]:
import numpy as np


In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
print(type(a))
a.shape #a is a one-dim vector,but obsecurely whether line vec or row vec?

<class 'numpy.ndarray'>


(3,)

In [6]:
a=a.reshape(1,-1)#reshape,-1是一个占位符
a

array([[1, 2, 3]])

In [8]:
a.shape#一行三列

(1, 3)

In [9]:
a=np.array([1,2,3,4,5,6])
a=a.reshape((2,-1))
a.shape

(2, 3)

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a=a.reshape((-1,2))

In [17]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a[2,0]

5

In [21]:
a[2,0]=55
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

### 然而，Numpy提供了很多自动生成数组的函数

In [22]:
#zeros
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
c=np.full((3,3),666)
c

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [27]:
d=np.eye(3)#生成单位矩阵
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
rand=np.random.random((3,4))
rand

array([[0.39986026, 0.65600129, 0.20757836, 0.85614226],
       [0.57611964, 0.44392753, 0.80062028, 0.07373838],
       [0.67031755, 0.45099361, 0.80000974, 0.27010323]])

# 下面来谈谈Indexing

In [3]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
#下面按照行列取出一个子数组
b=a[-2: ,1:3]
b

array([[ 6,  7],
       [10, 11]])

In [40]:
a[1,-2]
b

array([[ 6,  7],
       [10, 11]])

In [42]:
b.shape

(2, 2)

In [43]:
b=a[2,1:3]
b

array([10, 11])

In [44]:
b.shape

(2,)

In [45]:
b=a[2:3,1:3]
b

array([[10, 11]])

In [56]:
a

array([[ 1, 42,  3,  4],
       [ 5, 46,  7,  8],
       [ 9, 50, 11, 12]])

In [5]:
a[np.arange(3),1]+=10

In [6]:
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [52]:
np.arange(3)

array([0, 1, 2])

In [53]:
np.arange(3,7)

array([3, 4, 5, 6])

In [7]:
a[np.arange(3),[1,1,1]]+=10
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

In [8]:
result_index = a>10
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [9]:
a[result_index]

array([22, 26, 30, 11, 12])

In [10]:
a[a>10]

array([22, 26, 30, 11, 12])

 ### 元素数据类型

In [11]:
a=np.array([1,2])
a.dtype

dtype('int32')

In [12]:
a=np.array([1.1,2.2])
a.dtype

dtype('float64')

In [14]:
a=np.array([1,2.2])
a.dtype

dtype('float64')

In [15]:
a

array([1. , 2.2])

In [17]:
a=np.array([1.2,2.4],dtype=np.int64)
a

array([1, 2], dtype=int64)

### 数学运算与函数

In [18]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[6,5]])
a,b

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [6, 5]]))

In [19]:
a+b

array([[6, 8],
       [9, 9]])

In [20]:
np.add(a,b)

array([[6, 8],
       [9, 9]])

In [21]:
a

array([[1, 2],
       [3, 4]])

In [22]:
#substract is the same as plus operation

In [23]:
a*b
#矩阵乘法也是对应位的乘法

array([[ 5, 12],
       [18, 20]])

In [24]:
np.multiply(a,b)

array([[ 5, 12],
       [18, 20]])

In [25]:
a/b

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [27]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

### 以上都只是数组运算，而不是矩阵运算，矩阵运算需要用到dot

In [28]:
b=np.array([[1,2,3],[4,5,6]])
a.dot(b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [29]:
np.dot(a,b)

array([[ 9, 12, 15],
       [19, 26, 33]])

### 常用函数

In [30]:
a

array([[1, 2],
       [3, 4]])

In [31]:
np.sum(a)

10

In [32]:
np.sum(a,axis=0)#按列求和

array([4, 6])

In [33]:
np.sum(a,axis=1)#按行求和

array([3, 7])

In [34]:
np.mean(a)

2.5

In [35]:
np.mean(a,axis=0)

array([2., 3.])

In [36]:
np.mean(a,axis=1)

array([1.5, 3.5])

In [38]:
np.random.uniform(3,4)

3.8127192156982352

In [40]:
np.random.uniform(1,100)

74.14161382604938

In [41]:
a

array([[1, 2],
       [3, 4]])

In [42]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [43]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [44]:
np.tile(a,(2,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [46]:
a=np.array([[3,6,4,11],[50,11,3,1]])
a.argsort()

array([[0, 2, 1, 3],
       [3, 2, 1, 0]], dtype=int64)

In [47]:
a.argsort(axis=0)#按照列

array([[0, 0, 1, 1],
       [1, 1, 0, 0]], dtype=int64)

In [48]:
a

array([[ 3,  6,  4, 11],
       [50, 11,  3,  1]])

In [49]:
a.T#transpose

array([[ 3, 50],
       [ 6, 11],
       [ 4,  3],
       [11,  1]])

In [50]:
np.transpose(a)

array([[ 3, 50],
       [ 6, 11],
       [ 4,  3],
       [11,  1]])

### 最后来谈谈广播操作

In [57]:
a=np.array([[1,2,3],[2,3,4],[12,31,22],[2,2,2]])
a

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [12, 31, 22],
       [ 2,  2,  2]])

In [58]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [59]:
for i in range(4):
    a[i,:]+=b#数组整体加法
a
#But in Python we dont favor Circulate computing

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [13, 33, 25],
       [ 3,  4,  5]])

In [60]:
a+np.tile(b,(4,1)) 

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])

In [61]:
a

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [13, 33, 25],
       [ 3,  4,  5]])

In [62]:
a+b ##Broadcast 机制

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])